### ISSUE TITLE
Crash when I try to open world again

### ISSUE THREAD

**Issue by SpyC0der77** [Spiralio/infinicraft#18]
When I leave the world, and I try to join back, I crash. Here are my logs:

`[09:06:47] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 50732500ms or 1014650 ticks behind
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:48] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:302) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_20185(class_1140.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18670(class_1144.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[09:06:48] [Render thread/INFO]: Audio device was lost!
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on XFA243Y S (NVIDIA High Definition Audio)
[09:06:49] [Render thread/INFO]: Sound engine started
[09:06:49] [IO-Worker-17/INFO]: System default audio device has changed!
[09:06:49] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:49] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on XFA243Y S (NVIDIA High Definition Audio)
[09:06:49] [Render thread/INFO]: Sound engine started
[09:06:53] [IO-Worker-17/INFO]: System default audio device has changed!
[09:06:53] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:53] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:06:53] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (2- WH201A)
[09:06:53] [Render thread/INFO]: Sound engine started
[10:14:06] [Render thread/INFO]: Marked Minecraft Block as custom
[10:14:06] [ForkJoinPool.commonPool-worker-7/ERROR]: Failed to generate SD image for item Minecraft Block
java.util.concurrent.CompletionException: java.net.ConnectException
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException
	at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
[10:16:05] [ForkJoinPool.commonPool-worker-8/ERROR]: Failed to generate SD image for item Cobblestone
java.util.concurrent.CompletionException: java.net.ConnectException
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException
	at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
[10:16:18] [ForkJoinPool.commonPool-worker-8/ERROR]: Failed to generate SD image for item Redstone Torch
java.util.concurrent.CompletionException: java.net.ConnectException
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException
	at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
[10:16:19] [Render thread/INFO]: Loaded 106 advancements
[10:16:31] [ForkJoinPool.commonPool-worker-8/ERROR]: Failed to generate SD image for item Pickaxe
java.util.concurrent.CompletionException: java.net.ConnectException
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException
	at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	... 5 more
[10:16:31] [Render thread/INFO]: Marked Pickaxe as custom
[10:16:32] [Infinicraft Inference Thread Pool #28/ERROR]: Error during crafting
java.io.IOException: Unexpected response code: 429
	at net.spiralio.blocks.entity.InfinicrafterBlockEntity.processRecipe(InfinicrafterBlockEntity.java:396) ~[infinicraft-1.1.0.jar:?]
	at net.spiralio.blocks.entity.InfinicrafterBlockEntity.lambda$addToQueue$0(InfinicrafterBlockEntity.java:308) ~[infinicraft-1.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[10:26:48] [Server thread/INFO]: Saving and pausing game...
[10:26:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[10:26:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[10:26:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[10:26:48] [Server thread/INFO]: {MINECRAFT_USERNAME} lost connection: Disconnected
[10:26:48] [Server thread/INFO]: {MINECRAFT_USERNAME} left the game
[10:26:48] [Server thread/INFO]: Stopping singleplayer server as player logged out
[10:26:48] [Server thread/INFO]: Shutting down infinicraft backend server daemon
[10:26:50] [Server thread/INFO]: Stopping server
[10:26:50] [Infinicraft SD-API Thread Pool #1/INFO]: Ending infinicraft backend server daemon
[10:26:50] [Server thread/INFO]: Saving players
[10:26:50] [Server thread/INFO]: Saving worlds
[10:26:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[10:26:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[10:26:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[10:26:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[10:26:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[10:26:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[10:26:51] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[10:26:51] [Server thread/INFO]: Unloading server config for visualworkbench
[10:26:51] [Render thread/INFO]: Unloading server config for visualworkbench
[10:26:52] [Render thread/INFO]: Loaded 7 recipes
[10:26:52] [Render thread/INFO]: Loaded 1271 advancements
[10:26:52] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 191.2 ?s
[10:26:52] [Server thread/INFO]: Loading server config for visualworkbench
[10:26:52] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[10:26:52] [Server thread/INFO]: Generating keypair
[10:26:52] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:26:53] [Render thread/INFO]: Preparing spawn area: 0%
[10:26:53] [Render thread/INFO]: Preparing spawn area: 0%
[10:26:53] [Render thread/INFO]: Preparing spawn area: 24%
[10:26:54] [Render thread/INFO]: Time elapsed: 1224 ms
[10:26:54] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.RejectedExecutionException: Task net.spiralio.Infinicraft$$Lambda$10156/0x000001e12f1397a0@16cae405 rejected from java.util.concurrent.ThreadPoolExecutor@3a106ab8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 58]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:?]
	at net.spiralio.Infinicraft.lambda$onInitialize$4(Infinicraft.java:244) ~[infinicraft-1.1.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.3.1+a67ffb5d4f-acb38e9ac085196e.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zfk000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2414) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[10:26:54] [Server thread/ERROR]: This crash report has been saved to: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\Infinite Craft\crash-reports\crash-2024-07-29_10.26.54-server.txt
[10:26:54] [Server thread/INFO]: Shutting down infinicraft backend server daemon
[10:26:54] [Server thread/INFO]: Stopping server
[10:26:54] [Server thread/INFO]: Saving players
[10:26:54] [Server thread/INFO]: Saving worlds
`

**Comment by NonzeroCornet** [comment]
To be fixed. 👍

**Comment by SpyC0der77** [comment]
When?

**Comment by NonzeroCornet** [comment]
> When?

It's been fixed now lol
