### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SpyC0der77** [Spiralio/infinicraft#19]
[10:48:29] [Infinicraft Inference Thread Pool #7/ERROR]:
 Error during crafting
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 8 column 65 path $.Lucida Grande
	at com.google.gson.Gson.fromJson(Gson.java:1241) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
	at net.spiralio.blocks.entity.InfinicrafterBlockEntity.processRecipe(InfinicrafterBlockEntity.java:408) ~[infinicraft-1.1.0.jar:?]
	at net.spiralio.blocks.entity.InfinicrafterBlockEntity.lambda$addToQueue$0(InfinicrafterBlockEntity.java:308) ~[infinicraft-1.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 8 column 65 path $.Lucida Grande
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:539) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1256) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	... 10 more

**Comment by lolo45654** [comment]
This just seems to be the LLM not outputting Json.

**Comment by timaaos** [comment]
This needs to be handles by mod, ngl

**Comment by SpyC0der77** [comment]
> This needs to be handles by mod, ngl

Agreed
